#!/bin/bash

# Mac compatibility
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

PUBLIC_KEY_FOLDER=$(realpath ${PWD}/keys)

if [ ! -d $PUBLIC_KEY_FOLDER ]; then
  echo ">> The folder '$PUBLIC_KEY_FOLDER' does not exist." >&2
  exit 1;
fi

if [ -z "$1" ];
then
  echo ">> must pass file or string as argument"
  exit 1
fi

if [ -f "$1" ]; then
  echo ">> Encrypting file '$1'" >&2
  VALUE="$(cat $1)"
else
  VALUE="$1"
fi

echo -n "$VALUE" | docker run -v $PUBLIC_KEY_FOLDER:/keys/ -i --rm --name eyaml halberom/hiera-eyaml encrypt -o string --stdin
